project_name: prntenv

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: prntenv
      main: ./cmd/prntenv/
      env:
        - CGO_ENABLE=0
      ldflags:
        - -s -w
    id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, amd64, arm, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64, arm, arm64]

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/jcouture/{{.ProjectName}}"
    skip_push: false
    build_flag_templates:
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/jcouture/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/jcouture/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

upx:
  - enabled: true
    goos: [darwin, linux, windows]
    compress: best
    lzma: true
    brute: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: jcouture
      name: homebrew-prntenv
    folder: Formula
    homepage: https://github.com/jcouture/prntenv
    description: Utility to print out the names and values of the variables in the environment
    test: |
      system "#{bin}/prntenv"
